Added research.instructlab.ai
instructlab/dns-zones pull request #12
Opened 2024-11-07 22:02 UTC by jjasghar

This points research.instructlab.ai to xukai92.github.io

@mairin You'll need to tell @xukai92 to have to go to https://research.instructlab.ai/instructlab-research to get to this website. The subdirectory will need to probably be changed.

2024-11-08 03:47 UTC, xukai92 commented
thanks @jjasghar!
let me put the page under a subdomain/IP instead of a subdirectory somehow and come back to this

2025-02-02 04:02 UTC, xukai92 requested changes

2025-02-02 04:02 UTC, xukai92 commented on instructlab.ai.zone
> +research	IN		CNAME  xukai92.github.io.
```suggestion
research	IN		CNAME  Red-Hat-AI-Innovation-Team.github.io.
```

2025-02-02 04:02 UTC, xukai92 commented on instructlab.ai.zone
> +research	IN		CNAME  xukai92.github.io.
I created an org for our team and moved our GH Page repo to it.
Hopefully the subdir is not needed any more too.

2025-02-02 04:09 UTC, xukai92 approved these changes

2025-02-02 04:15 UTC, merged

2025-02-02 04:24 UTC, xukai92 commented
@jjasghar I made some changes to account for the new GH Page link (red-hat-ai-innovation-team.github.io) but it doesn't seem to be working after merge.
Did I do anything wrong here?

2025-02-03 14:32 UTC, jjasghar commented
I'll do some research, I'm traveling at the moment, but I'll dig into this asap.

2025-02-03 14:36 UTC, jjasghar commented
Ah! your DNS might be set up incorrectly, (or at least I need to take a look) _inside_ Github. Can you add me as an "owner" `jjasghar` and then I can see what the configuration is?

2025-02-03 15:12 UTC, xukai92 commented
just added to the repo with admin access

2025-02-03 15:16 UTC, jjasghar commented
Looks like there's a bunch more steps that need to be ran :(

https://docs.github.com/pages/configuring-a-custom-domain-for-your-github-pages-site/verifying-your-custom-domain-for-github-pages

I guess because it's a completely different org, not in the instructlab.ai namespace. I'll see what I can do when I'm back in my office.

2025-02-10 19:59 UTC, jjasghar commented
I think https://github.com/instructlab/dns-zones/pull/14 is required, but now I need to figure out what I did wrong.